INFO 2022-08-31 14:16:54,833 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:21:48,558 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\models.py changed, reloading.
INFO 2022-08-31 14:21:49,517 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:22:31,621 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\models.py changed, reloading.
INFO 2022-08-31 14:22:32,417 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:22:55,305 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\models.py changed, reloading.
INFO 2022-08-31 14:22:55,998 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:23:16,712 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\models.py changed, reloading.
INFO 2022-08-31 14:23:17,536 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:25:18,616 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\models.py changed, reloading.
INFO 2022-08-31 14:25:19,458 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:25:46,558 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\models.py changed, reloading.
INFO 2022-08-31 14:25:47,447 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:27:30,286 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blogproject\urls.py changed, reloading.
INFO 2022-08-31 14:27:31,018 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:27:56,021 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blogproject\urls.py changed, reloading.
INFO 2022-08-31 14:27:56,776 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:29:50,243 basehttp 187 "GET / HTTP/1.1" 200 18175
INFO 2022-08-31 14:29:54,950 basehttp 187 "GET /all/rss/ HTTP/1.1" 200 276245
INFO 2022-08-31 14:30:45,965 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:30:48,567 basehttp 187 "GET / HTTP/1.1" 200 18175
ERROR 2022-08-31 14:30:52,627 log 241 Internal Server Error: /posts/5/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 59, in get
    response = super().get(request, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 80, in get_object
    post.toc = m.group(1) if m is not None else ''
AttributeError: can't set attribute
ERROR 2022-08-31 14:30:52,629 basehttp 187 "GET /posts/5/ HTTP/1.1" 500 88787
INFO 2022-08-31 14:31:44,764 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:31:46,635 basehttp 187 "GET / HTTP/1.1" 200 18175
ERROR 2022-08-31 14:31:49,203 log 241 Internal Server Error: /posts/5/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 59, in get
    response = super().get(request, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 80, in get_object
    post.toc = m.group(1) if m is not None else ''
AttributeError: can't set attribute
ERROR 2022-08-31 14:31:49,205 basehttp 187 "GET /posts/5/ HTTP/1.1" 500 88787
INFO 2022-08-31 14:36:26,592 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\models.py changed, reloading.
INFO 2022-08-31 14:36:27,380 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-08-31 14:36:36,090 log 241 Internal Server Error: /posts/5/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 59, in get
    response = super().get(request, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 80, in get_object
    post.toc = m.group(1) if m is not None else ''
AttributeError: can't set attribute
ERROR 2022-08-31 14:36:36,092 basehttp 187 "GET /posts/5/ HTTP/1.1" 500 88924
ERROR 2022-08-31 14:36:38,778 log 241 Internal Server Error: /posts/5/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 59, in get
    response = super().get(request, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 80, in get_object
    post.toc = m.group(1) if m is not None else ''
AttributeError: can't set attribute
ERROR 2022-08-31 14:36:38,779 basehttp 187 "GET /posts/5/ HTTP/1.1" 500 88787
INFO 2022-08-31 14:39:22,210 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 14:39:25,485 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 29816
WARNING 2022-08-31 14:39:25,563 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 14:39:25,563 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 3369
WARNING 2022-08-31 14:39:25,565 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 14:39:25,566 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 3351
INFO 2022-08-31 14:39:35,380 basehttp 187 "GET /all/rss/ HTTP/1.1" 200 276245
INFO 2022-08-31 14:40:55,344 basehttp 187 "GET /all/rss/ HTTP/1.1" 200 276245
INFO 2022-08-31 14:41:58,210 basehttp 187 "GET /all/rss/ HTTP/1.1" 200 276245
INFO 2022-08-31 14:41:59,069 basehttp 187 "GET /all/rss/ HTTP/1.1" 200 276245
WARNING 2022-08-31 14:41:59,184 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 14:41:59,185 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 3369
INFO 2022-08-31 14:42:12,100 basehttp 187 "GET /posts/60/ HTTP/1.1" 200 14660
INFO 2022-08-31 14:42:23,428 basehttp 187 "GET /posts/151/ HTTP/1.1" 200 13761
INFO 2022-08-31 14:42:31,533 basehttp 187 "GET /posts/138/ HTTP/1.1" 200 15377
INFO 2022-08-31 14:42:45,100 basehttp 187 "GET /posts/146/ HTTP/1.1" 200 15220
ERROR 2022-08-31 14:46:28,374 log 241 Internal Server Error: /
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Users\18203\blog\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'admin' not found. 'admin' is not a valid view function or pattern name.
ERROR 2022-08-31 14:46:28,377 basehttp 187 "GET / HTTP/1.1" 500 156311
INFO 2022-08-31 14:47:10,622 basehttp 187 "GET / HTTP/1.1" 200 18165
INFO 2022-08-31 14:47:12,229 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 14:47:12,285 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 14:47:12,334 basehttp 187 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2022-08-31 14:47:12,335 basehttp 187 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2022-08-31 14:47:12,336 basehttp 187 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2022-08-31 14:47:12,337 basehttp 187 "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2022-08-31 14:47:12,337 basehttp 187 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2022-08-31 14:47:12,339 basehttp 187 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2022-08-31 14:47:12,341 basehttp 187 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2022-08-31 14:47:12,387 basehttp 187 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2022-08-31 14:47:12,394 basehttp 187 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2022-08-31 14:48:34,819 basehttp 187 "GET / HTTP/1.1" 200 18165
INFO 2022-08-31 14:48:49,655 basehttp 187 "GET /posts/94/ HTTP/1.1" 200 16602
INFO 2022-08-31 15:07:43,019 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\views.py changed, reloading.
INFO 2022-08-31 15:07:43,790 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:08:27,921 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\views.py changed, reloading.
INFO 2022-08-31 15:08:28,603 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:09:35,244 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\views.py changed, reloading.
INFO 2022-08-31 15:09:35,944 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:10:44,548 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\urls.py changed, reloading.
INFO 2022-08-31 15:10:45,453 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:11:18,150 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:11:22,225 basehttp 187 "GET / HTTP/1.1" 200 18181
INFO 2022-08-31 15:11:32,578 basehttp 187 "GET /search/? HTTP/1.1" 302 0
INFO 2022-08-31 15:11:32,623 basehttp 187 "GET / HTTP/1.1" 200 18463
INFO 2022-08-31 15:11:41,091 basehttp 187 "GET /search/? HTTP/1.1" 302 0
INFO 2022-08-31 15:11:41,160 basehttp 187 "GET / HTTP/1.1" 200 18463
INFO 2022-08-31 15:12:18,572 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:12:39,378 basehttp 187 "GET /search/? HTTP/1.1" 302 0
INFO 2022-08-31 15:12:39,446 basehttp 187 "GET / HTTP/1.1" 200 18464
INFO 2022-08-31 15:14:18,581 basehttp 187 "GET /search/?q=mark HTTP/1.1" 200 34585
INFO 2022-08-31 15:15:18,073 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\views.py changed, reloading.
INFO 2022-08-31 15:15:18,863 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:15:21,339 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:15:32,998 basehttp 187 "GET /search/?q=mark HTTP/1.1" 200 34585
INFO 2022-08-31 15:15:57,544 basehttp 187 "GET /search/?q=even HTTP/1.1" 200 65276
INFO 2022-08-31 15:16:06,640 basehttp 187 "GET /posts/94/ HTTP/1.1" 200 16619
INFO 2022-08-31 15:17:14,590 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\views.py changed, reloading.
INFO 2022-08-31 15:17:15,393 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:20:24,391 basehttp 187 "GET / HTTP/1.1" 200 18182
WARNING 2022-08-31 15:20:29,611 log 241 Not Found: /about.html
WARNING 2022-08-31 15:20:29,612 basehttp 187 "GET /about.html HTTP/1.1" 404 3511
INFO 2022-08-31 15:35:37,137 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:35:38,989 basehttp 187 "GET / HTTP/1.1" 200 18182
WARNING 2022-08-31 15:35:40,476 log 241 Not Found: /about.html
WARNING 2022-08-31 15:35:40,476 basehttp 187 "GET /about.html HTTP/1.1" 404 3678
INFO 2022-08-31 15:36:13,996 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\views.py changed, reloading.
INFO 2022-08-31 15:36:14,733 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:36:30,300 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-08-31 15:36:37,209 log 241 Not Found: /about.html
WARNING 2022-08-31 15:36:37,210 basehttp 187 "GET /about.html HTTP/1.1" 404 3678
INFO 2022-08-31 15:37:11,320 basehttp 187 "GET /about HTTP/1.1" 301 0
INFO 2022-08-31 15:37:11,373 basehttp 187 "GET /about/ HTTP/1.1" 200 11302
WARNING 2022-08-31 15:37:11,456 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 15:37:11,457 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 3696
INFO 2022-08-31 15:37:49,122 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\urls.py changed, reloading.
INFO 2022-08-31 15:37:50,040 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:38:24,926 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\urls.py changed, reloading.
INFO 2022-08-31 15:38:25,621 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:38:27,685 basehttp 187 "GET / HTTP/1.1" 200 18179
INFO 2022-08-31 15:38:29,064 basehttp 187 "GET /about/ HTTP/1.1" 200 11299
WARNING 2022-08-31 15:38:29,116 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 15:38:29,117 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 3696
WARNING 2022-08-31 15:38:42,036 log 241 Not Found: /about/admin
WARNING 2022-08-31 15:38:42,037 basehttp 187 "GET /about/admin HTTP/1.1" 404 3681
WARNING 2022-08-31 15:38:43,809 log 241 Not Found: /about/admin
WARNING 2022-08-31 15:38:43,810 basehttp 187 "GET /about/admin HTTP/1.1" 404 3681
INFO 2022-08-31 15:38:47,075 basehttp 187 "GET / HTTP/1.1" 200 18179
INFO 2022-08-31 15:38:48,110 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 15:38:48,187 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 15:38:50,298 basehttp 187 "GET /about/ HTTP/1.1" 200 11299
WARNING 2022-08-31 15:38:50,343 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 15:38:50,343 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 3696
WARNING 2022-08-31 15:38:52,222 log 241 Not Found: /about/admin
WARNING 2022-08-31 15:38:52,222 basehttp 187 "GET /about/admin HTTP/1.1" 404 3681
WARNING 2022-08-31 15:38:58,412 log 241 Not Found: /about/contact.html
WARNING 2022-08-31 15:38:58,413 basehttp 187 "GET /about/contact.html HTTP/1.1" 404 3702
INFO 2022-08-31 15:39:02,333 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 29820
WARNING 2022-08-31 15:39:02,394 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 15:39:02,396 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 15:39:02,396 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 3687
WARNING 2022-08-31 15:39:02,397 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 3705
WARNING 2022-08-31 15:39:03,497 log 241 Not Found: /posts/5/admin
WARNING 2022-08-31 15:39:03,498 basehttp 187 "GET /posts/5/admin HTTP/1.1" 404 3687
INFO 2022-08-31 15:45:13,020 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 15:45:17,052 basehttp 187 "GET / HTTP/1.1" 200 18181
INFO 2022-08-31 15:45:18,766 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 15:45:18,790 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 15:45:20,891 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 15:45:20,903 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 15:45:24,095 basehttp 187 "GET /about/ HTTP/1.1" 200 11301
WARNING 2022-08-31 15:45:24,143 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 15:45:24,144 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 3863
INFO 2022-08-31 15:45:26,178 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 15:45:26,189 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 15:45:41,262 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 29822
WARNING 2022-08-31 15:45:41,315 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 15:45:41,316 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 15:45:41,317 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 3854
WARNING 2022-08-31 15:45:41,317 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 3872
WARNING 2022-08-31 15:45:48,585 log 241 Not Found: /about/contact.html
WARNING 2022-08-31 15:45:48,585 basehttp 187 "GET /about/contact.html HTTP/1.1" 404 3869
INFO 2022-08-31 15:49:24,021 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\urls.py changed, reloading.
INFO 2022-08-31 15:49:24,788 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-08-31 15:49:29,885 log 241 Not Found: /about/contact.html
WARNING 2022-08-31 15:49:29,885 basehttp 187 "GET /about/contact.html HTTP/1.1" 404 4040
INFO 2022-08-31 15:50:20,052 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\views.py changed, reloading.
INFO 2022-08-31 15:50:20,896 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-08-31 15:50:25,583 log 241 Not Found: /about/contact.html
WARNING 2022-08-31 15:50:25,585 basehttp 187 "GET /about/contact.html HTTP/1.1" 404 4040
WARNING 2022-08-31 15:50:28,498 log 241 Not Found: /about/contact.html
WARNING 2022-08-31 15:50:28,498 basehttp 187 "GET /about/contact.html HTTP/1.1" 404 4040
WARNING 2022-08-31 15:50:40,165 log 241 Not Found: /contact.html
WARNING 2022-08-31 15:50:40,165 basehttp 187 "GET /contact.html HTTP/1.1" 404 4022
INFO 2022-08-31 15:51:18,848 autoreload 677 Watching for file changes with StatReloader
WARNING 2022-08-31 15:51:25,945 log 241 Not Found: /contact.html
WARNING 2022-08-31 15:51:25,946 basehttp 187 "GET /contact.html HTTP/1.1" 404 4022
WARNING 2022-08-31 15:51:26,838 log 241 Not Found: /contact.html
WARNING 2022-08-31 15:51:26,839 basehttp 187 "GET /contact.html HTTP/1.1" 404 4022
INFO 2022-08-31 15:51:30,583 basehttp 187 "GET /about/ HTTP/1.1" 200 11298
WARNING 2022-08-31 15:51:30,630 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 15:51:30,631 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 15:51:32,159 basehttp 187 "GET /contact/ HTTP/1.1" 200 10631
INFO 2022-08-31 15:51:43,403 basehttp 187 "GET /about/ HTTP/1.1" 200 11298
WARNING 2022-08-31 15:51:43,446 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 15:51:43,446 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 15:51:47,669 basehttp 187 "GET / HTTP/1.1" 200 18178
INFO 2022-08-31 15:54:07,683 basehttp 187 "GET / HTTP/1.1" 200 18164
INFO 2022-08-31 15:54:11,401 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 29805
WARNING 2022-08-31 15:54:11,449 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 15:54:11,450 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 15:54:11,451 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
WARNING 2022-08-31 15:54:11,451 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
INFO 2022-08-31 16:00:45,779 basehttp 187 "GET /about/ HTTP/1.1" 200 9646
INFO 2022-08-31 16:01:01,847 basehttp 187 "GET /about/ HTTP/1.1" 200 11247
WARNING 2022-08-31 16:01:01,906 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:01:01,906 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:01:04,592 basehttp 187 "GET / HTTP/1.1" 200 18127
INFO 2022-08-31 16:02:07,718 basehttp 187 "GET /contact/ HTTP/1.1" 200 9678
INFO 2022-08-31 16:02:10,933 basehttp 187 "GET /contact/ HTTP/1.1" 200 9678
INFO 2022-08-31 16:02:47,572 basehttp 187 "GET /contact/ HTTP/1.1" 200 9678
INFO 2022-08-31 16:02:52,537 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 16:02:54,415 basehttp 187 "GET /contact/ HTTP/1.1" 200 10580
INFO 2022-08-31 16:03:54,412 basehttp 187 "GET /contact/ HTTP/1.1" 200 5856
ERROR 2022-08-31 16:03:56,517 log 241 Internal Server Error: /
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'show_recent_posts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 49: 'show_recent_posts'. Did you forget to register or load this tag?
ERROR 2022-08-31 16:03:56,520 basehttp 187 "GET / HTTP/1.1" 500 164471
INFO 2022-08-31 16:04:43,020 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 16:04:44,053 basehttp 187 "GET / HTTP/1.1" 200 13403
INFO 2022-08-31 16:04:46,550 basehttp 187 "GET / HTTP/1.1" 200 13403
INFO 2022-08-31 16:04:49,872 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 16:04:49,898 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 16:04:51,837 basehttp 187 "GET /about/ HTTP/1.1" 200 6523
WARNING 2022-08-31 16:04:51,884 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:04:51,885 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:04:53,327 basehttp 187 "GET /contact/ HTTP/1.1" 200 5856
INFO 2022-08-31 16:04:56,039 basehttp 187 "GET / HTTP/1.1" 200 13403
INFO 2022-08-31 16:05:12,793 basehttp 187 "GET / HTTP/1.1" 200 13403
INFO 2022-08-31 16:06:01,039 basehttp 187 "GET / HTTP/1.1" 200 18121
INFO 2022-08-31 16:06:04,791 basehttp 187 "GET / HTTP/1.1" 200 18121
INFO 2022-08-31 16:06:31,026 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 16:06:31,045 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 16:06:32,663 basehttp 187 "GET /about/ HTTP/1.1" 200 6523
WARNING 2022-08-31 16:06:32,712 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:06:32,712 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:06:35,126 basehttp 187 "GET /contact/ HTTP/1.1" 200 5856
INFO 2022-08-31 16:06:38,881 basehttp 187 "GET /about/ HTTP/1.1" 200 6523
WARNING 2022-08-31 16:06:38,923 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:06:38,923 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:06:40,824 basehttp 187 "GET / HTTP/1.1" 200 18121
INFO 2022-08-31 16:09:27,338 basehttp 187 "GET / HTTP/1.1" 200 18135
INFO 2022-08-31 16:09:31,908 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 16:09:31,925 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 16:09:33,629 basehttp 187 "GET /about/ HTTP/1.1" 200 6544
WARNING 2022-08-31 16:09:33,677 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:09:33,679 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:09:35,606 basehttp 187 "GET /contact/ HTTP/1.1" 200 5877
INFO 2022-08-31 16:09:38,395 basehttp 187 "GET / HTTP/1.1" 200 18135
INFO 2022-08-31 16:09:45,380 basehttp 187 "GET / HTTP/1.1" 200 18135
INFO 2022-08-31 16:09:46,021 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 16:09:46,034 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 16:09:48,050 basehttp 187 "GET /about/ HTTP/1.1" 200 6544
WARNING 2022-08-31 16:09:48,098 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:09:48,099 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:09:50,356 basehttp 187 "GET /contact/ HTTP/1.1" 200 5877
INFO 2022-08-31 16:09:54,148 basehttp 187 "GET / HTTP/1.1" 200 18135
INFO 2022-08-31 16:10:18,992 basehttp 187 "GET / HTTP/1.1" 200 18135
INFO 2022-08-31 16:10:21,445 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 24126
WARNING 2022-08-31 16:10:21,491 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:10:21,493 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:10:21,493 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
WARNING 2022-08-31 16:10:21,494 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
INFO 2022-08-31 16:11:21,534 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 24118
WARNING 2022-08-31 16:11:21,592 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:11:21,595 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:11:21,596 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
WARNING 2022-08-31 16:11:21,596 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
INFO 2022-08-31 16:12:18,241 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 24119
WARNING 2022-08-31 16:12:18,297 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:12:18,299 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:12:18,300 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
WARNING 2022-08-31 16:12:18,300 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
INFO 2022-08-31 16:12:26,401 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 24119
WARNING 2022-08-31 16:12:26,451 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:12:26,452 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
WARNING 2022-08-31 16:12:26,455 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:12:26,456 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
INFO 2022-08-31 16:15:05,607 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 24119
WARNING 2022-08-31 16:15:05,688 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:15:05,691 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
WARNING 2022-08-31 16:15:05,700 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:15:05,700 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
INFO 2022-08-31 16:16:40,741 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 24124
WARNING 2022-08-31 16:16:40,801 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:16:40,803 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:16:40,803 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
WARNING 2022-08-31 16:16:40,804 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
INFO 2022-08-31 16:16:52,611 basehttp 187 "GET / HTTP/1.1" 200 18141
INFO 2022-08-31 16:18:14,918 basehttp 187 "GET / HTTP/1.1" 200 18154
INFO 2022-08-31 16:18:19,211 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 16:18:19,342 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 16:18:21,273 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 25160
WARNING 2022-08-31 16:18:21,317 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:18:21,319 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:18:21,319 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
WARNING 2022-08-31 16:18:21,320 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
INFO 2022-08-31 16:18:40,255 basehttp 187 "GET /about/ HTTP/1.1" 200 6654
WARNING 2022-08-31 16:18:40,305 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:18:40,305 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:19:19,755 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 25216
WARNING 2022-08-31 16:19:19,820 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:19:19,821 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
WARNING 2022-08-31 16:19:19,823 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:19:19,824 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
INFO 2022-08-31 16:19:23,691 basehttp 187 "GET / HTTP/1.1" 200 18081
INFO 2022-08-31 16:19:29,920 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 25216
WARNING 2022-08-31 16:19:29,972 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:19:29,974 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:19:29,974 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
WARNING 2022-08-31 16:19:29,974 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
INFO 2022-08-31 16:19:56,786 basehttp 187 "GET /about/ HTTP/1.1" 200 6710
WARNING 2022-08-31 16:19:56,835 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:19:56,836 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:19:58,049 basehttp 187 "GET /contact/ HTTP/1.1" 200 6043
INFO 2022-08-31 16:19:59,130 basehttp 187 "GET / HTTP/1.1" 200 18081
INFO 2022-08-31 16:21:03,825 basehttp 187 "GET / HTTP/1.1" 200 18080
INFO 2022-08-31 16:21:05,878 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 25215
WARNING 2022-08-31 16:21:05,925 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:21:05,926 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:21:05,927 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
WARNING 2022-08-31 16:21:05,928 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
INFO 2022-08-31 16:21:14,264 basehttp 187 "GET / HTTP/1.1" 200 18080
INFO 2022-08-31 16:21:16,260 basehttp 187 "GET /posts/138/ HTTP/1.1" 200 10775
ERROR 2022-08-31 16:23:26,510 log 241 Internal Server Error: /posts/5/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'aside' appears more than once
ERROR 2022-08-31 16:23:26,513 basehttp 187 "GET /posts/5/ HTTP/1.1" 500 165001
ERROR 2022-08-31 16:23:33,864 log 241 Internal Server Error: /posts/5/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'aside' appears more than once
ERROR 2022-08-31 16:23:33,866 basehttp 187 "GET /posts/5/ HTTP/1.1" 500 165529
INFO 2022-08-31 16:23:40,441 autoreload 677 Watching for file changes with StatReloader
ERROR 2022-08-31 16:23:42,843 log 241 Internal Server Error: /posts/5/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'aside' appears more than once
ERROR 2022-08-31 16:23:42,847 basehttp 187 "GET /posts/5/ HTTP/1.1" 500 165529
ERROR 2022-08-31 16:24:21,420 log 241 Internal Server Error: /posts/5/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: index.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Users\18203\blog\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2022-08-31 16:24:21,422 basehttp 187 "GET /posts/5/ HTTP/1.1" 500 131550
INFO 2022-08-31 16:24:29,171 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 25215
WARNING 2022-08-31 16:24:29,249 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:24:29,250 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:24:29,251 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
WARNING 2022-08-31 16:24:29,251 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
INFO 2022-08-31 16:25:19,965 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 25215
WARNING 2022-08-31 16:25:20,028 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:25:20,030 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:25:20,031 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
WARNING 2022-08-31 16:25:20,031 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
INFO 2022-08-31 16:25:59,420 basehttp 187 "GET /posts/5/ HTTP/1.1" 200 29708
WARNING 2022-08-31 16:25:59,481 log 241 Not Found: /posts/5/example.jpg
WARNING 2022-08-31 16:25:59,483 log 241 Not Found: /posts/5/a.jpg
WARNING 2022-08-31 16:25:59,483 basehttp 187 "GET /posts/5/a.jpg HTTP/1.1" 404 4025
WARNING 2022-08-31 16:25:59,484 basehttp 187 "GET /posts/5/example.jpg HTTP/1.1" 404 4043
INFO 2022-08-31 16:26:03,885 basehttp 187 "GET / HTTP/1.1" 200 18080
INFO 2022-08-31 16:26:06,690 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 16:26:06,709 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 16:26:08,400 basehttp 187 "GET /about/ HTTP/1.1" 200 6709
WARNING 2022-08-31 16:26:08,454 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:26:08,455 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:26:10,797 basehttp 187 "GET /contact/ HTTP/1.1" 200 6042
INFO 2022-08-31 16:26:14,028 basehttp 187 "GET /about/ HTTP/1.1" 200 6709
WARNING 2022-08-31 16:26:14,069 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:26:14,070 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:26:34,390 basehttp 187 "GET /contact/ HTTP/1.1" 200 6042
INFO 2022-08-31 16:26:42,308 basehttp 187 "GET /about/ HTTP/1.1" 200 6709
WARNING 2022-08-31 16:26:42,349 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:26:42,350 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
ERROR 2022-08-31 16:28:51,600 log 241 Internal Server Error: /about/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 78, in about
    return render(request, 'about.html')
  File "D:\Users\18203\blog\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\18203\blog\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\18203\blog\lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
  File "D:\Users\18203\blog\lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '/static/img/me.jpg' from 'blog/static/img/me.jpg'
ERROR 2022-08-31 16:28:51,603 basehttp 187 "GET /about/ HTTP/1.1" 500 187614
INFO 2022-08-31 16:30:29,239 basehttp 187 "GET /about/ HTTP/1.1" 200 6826
WARNING 2022-08-31 16:30:29,320 log 241 Not Found: /about/img/me.jpg
WARNING 2022-08-31 16:30:29,321 basehttp 187 "GET /about/img/me.jpg HTTP/1.1" 404 4034
INFO 2022-08-31 16:30:29,599 basehttp 187 "GET /static/blog/img/me.jpg HTTP/1.1" 200 63353
INFO 2022-08-31 16:30:46,371 basehttp 187 "GET /about/ HTTP/1.1" 200 6749
INFO 2022-08-31 16:33:18,129 basehttp 187 "GET /contact/ HTTP/1.1" 200 6042
INFO 2022-08-31 16:33:21,042 basehttp 187 "GET / HTTP/1.1" 200 18080
INFO 2022-08-31 16:33:24,068 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 16:33:24,084 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 16:33:26,248 basehttp 187 "GET /about/ HTTP/1.1" 200 6749
INFO 2022-08-31 16:33:27,815 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 16:33:27,828 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 16:33:42,066 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 16:33:44,907 basehttp 187 "GET / HTTP/1.1" 200 18080
WARNING 2022-08-31 16:33:46,209 log 241 Not Found: /favicon.ico
WARNING 2022-08-31 16:33:46,210 basehttp 187 "GET /favicon.ico HTTP/1.1" 404 4019
INFO 2022-08-31 16:34:02,709 basehttp 187 "GET /archives/2022/3/ HTTP/1.1" 200 17792
INFO 2022-08-31 16:34:05,600 basehttp 187 "GET /archives/2022/6/ HTTP/1.1" 200 17748
INFO 2022-08-31 16:34:09,463 basehttp 187 "GET /archives/2022/1/ HTTP/1.1" 200 17714
INFO 2022-08-31 16:39:08,678 basehttp 187 "GET /posts/59/ HTTP/1.1" 200 12864
INFO 2022-08-31 16:39:14,268 basehttp 187 "GET /posts/59/ HTTP/1.1" 200 12864
INFO 2022-08-31 16:39:20,517 basehttp 187 "GET /contact/ HTTP/1.1" 200 6042
ERROR 2022-08-31 16:40:54,328 log 241 Internal Server Error: /contact/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 164, in contact
    return render(request, 'contact.html')
  File "D:\Users\18203\blog\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\library.py", line 278, in render
    return t.render(new_context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Users\18203\blog\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'comment' with arguments '('',)' not found. 1 pattern(s) tried: ['comment/(?P<post_pk>[0-9]+)\\Z']
ERROR 2022-08-31 16:40:54,338 basehttp 187 "GET /contact/ HTTP/1.1" 500 194787
ERROR 2022-08-31 16:42:25,323 log 241 Internal Server Error: /contact/
Traceback (most recent call last):
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Users\18203\blog\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\18203\Desktop\work\blogproject\blog\views.py", line 164, in contact
    return render(request, 'contact.html')
  File "D:\Users\18203\blog\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Users\18203\blog\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\library.py", line 278, in render
    return t.render(new_context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Users\18203\blog\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "D:\Users\18203\blog\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Users\18203\blog\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Users\18203\blog\lib\site-packages\django\urls\resolvers.py", line 803, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'comment' with arguments '('',)' not found. 1 pattern(s) tried: ['comment/(?P<post_pk>[0-9]+)\\Z']
ERROR 2022-08-31 16:42:25,328 basehttp 187 "GET /contact/ HTTP/1.1" 500 194223
INFO 2022-08-31 16:50:02,583 autoreload 266 D:\Users\18203\Desktop\work\blogproject\blog\views.py changed, reloading.
INFO 2022-08-31 16:50:03,544 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 16:52:21,463 autoreload 677 Watching for file changes with StatReloader
INFO 2022-08-31 16:52:25,929 basehttp 187 "GET /contact/ HTTP/1.1" 200 5125
INFO 2022-08-31 16:52:27,694 basehttp 187 "GET /about/ HTTP/1.1" 200 6749
INFO 2022-08-31 16:52:28,525 basehttp 187 "GET /admin/ HTTP/1.1" 302 0
INFO 2022-08-31 16:52:28,562 basehttp 187 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2220
INFO 2022-08-31 16:52:30,596 basehttp 187 "GET / HTTP/1.1" 200 18080
